### ISSUE TITLE
Example link gets 404

### ISSUE THREAD

**Issue by chriswhong** [mhkeller/cartodb-embeds#8]
http://mhkeller.github.io/cartob-embeds

**Comment by chriswhong** [comment]
http://mhkeller.github.io/cartob-embeds

**Comment by mhkeller** [comment]
Just redid the examples page and as a bonus I didn't link to javascript folders that were being .gitignored, so that should help. Due to potential conflicts with how your site might load jQuery, it would probably be best to wait to wait till I finish https://github.com/mhkeller/cartodb-embeds/issues/6, which I'm hoping is later today.

http://mhkeller.github.io/cartodb-embeds/examples/index.html
https://github.com/mhkeller/cartodb-embeds/commit/33198435ea4038a1b9bc361c8b26809cc29eb5f3

**Comment by mhkeller** [comment]
#6 is done fyi. That was easier than expected.
